version: '3.8'

services:
  catalog-api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://catalog_user:catalog_password@postgres:5432/catalog_db
      - DEBUG=false
    volumes:
      - ./version: '3.8'

services:
  catalog-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/catalog.db
    restart: unless-stopped

